version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DB_NAME
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "3306:${MYSQL_PORT}"
    volumes:
      - ./mysqldb_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  mysqldb_volume: