version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CARD_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CARD_MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

volumes:
  mongodb_data:
